# Generated by Django 6.0.3 on 2026-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='free_shipping_text',
            field=models.CharField(default='Free shipping on all your order', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_footer_text',
            field=models.CharField(default='Freshness Score Guaranteed Quality Products', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
