# Generated by Django 6.0.3 on 2026-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_newspost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_animation',
            field=models.CharField(choices=[('pulse', 'Pulse'), ('shine', 'Shine'), ('bounce', 'Bounce'), ('none', 'No Animation')], default='pulse', max_length=30),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_animation',
            field=models.CharField(choices=[('fade-up', 'Fade Up'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('none', 'No Animation')], default='fade-up', max_length=30),
        ),
    ]
