# Generated by Django 6.0.3 on 2026-06-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_footercolumn_footerinstagramimage_footersetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDiscountBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_text', models.CharField(default='79% Discount', max_length=80)),
                ('subtitle', models.CharField(default='on your first order', max_length=120)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/sidebar-discount/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop Discount Banner',
                'verbose_name_plural': 'Shop Discount Banner',
            },
        ),
        migrations.CreateModel(
            name='ShopPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Categories', max_length=120)),
                ('breadcrumb_text', models.CharField(default='Categories', max_length=120)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='shop/banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop Page Banner',
                'verbose_name_plural': 'Shop Page Banner',
            },
        ),
        migrations.CreateModel(
            name='ShopPopularTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('filter_value', models.CharField(help_text='Example: low fat, vegetarian, fruit', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop Popular Tag',
                'verbose_name_plural': 'Shop Popular Tags',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopPriceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='₹0 - ₹500', max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop Price Filter',
                'verbose_name_plural': 'Shop Price Filters',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopRatingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='4.0 & up', max_length=100)),
                ('rating_value', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop Rating Filter',
                'verbose_name_plural': 'Shop Rating Filters',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_sale_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Shop Sale Product',
                'verbose_name_plural': 'Shop Sale Products',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
