# Generated by Django 6.0.3 on 2026-06-18 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shopdiscountbanner_shoppagebanner_shoppopulartag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOfMonthBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(default='BEST DEALS', max_length=80)),
                ('title', models.CharField(default='Sale of the Month', max_length=150)),
                ('discount_text', models.CharField(default='56% OFF', max_length=80)),
                ('days', models.PositiveIntegerField(default=0)),
                ('hours', models.PositiveIntegerField(default=2)),
                ('minutes', models.PositiveIntegerField(default=18)),
                ('seconds', models.PositiveIntegerField(default=46)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sale-month/')),
                ('bg_color', models.CharField(default='#002603', max_length=20)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sale of the Month Banner',
                'verbose_name_plural': 'Sale of the Month Banners',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
