# Generated by Django 6.0.3 on 2026-06-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saleofmonthbanner_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Shopping Cart', max_length=120)),
                ('breadcrumb_text', models.CharField(default='Home > Category > Vegetables > Shopping cart', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='cart/banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cart Page Banner',
                'verbose_name_plural': 'Cart Page Banner',
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon Code',
                'verbose_name_plural': 'Coupon Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CartRelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_related_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Cart Related Product',
                'verbose_name_plural': 'Cart Related Products',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
