# Generated by Django 6.0.3 on 2026-06-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cartpagebanner_couponcode_cartrelatedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Brand Logo', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/brands/')),
                ('text_logo', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Brand Logo',
                'verbose_name_plural': 'Blog Brand Logos',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogDiscountBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_text', models.CharField(default='79% Discount', max_length=80)),
                ('subtitle', models.CharField(default='on your first order', max_length=120)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/sidebar-discount/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Discount Banner',
                'verbose_name_plural': 'Blog Discount Banner',
            },
        ),
        migrations.CreateModel(
            name='BlogGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gallery Image', max_length=100)),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Gallery Image',
                'verbose_name_plural': 'Blog Gallery Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog', max_length=120)),
                ('breadcrumb_text', models.CharField(default='Blog', max_length=120)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='blog/banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Page Banner',
                'verbose_name_plural': 'Blog Page Banner',
            },
        ),
        migrations.CreateModel(
            name='BlogPopularTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('filter_value', models.CharField(help_text='Example: food, healthy, organic', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Popular Tag',
                'verbose_name_plural': 'Blog Popular Tags',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('excerpt', models.TextField(blank=True)),
                ('author_name', models.CharField(default='Admin', max_length=80)),
                ('date_label', models.CharField(default='18 NOV', max_length=30)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('is_video', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, default='')),
                ('read_more_text', models.CharField(default='Read More', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogRecentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_items', to='core.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Recently Added',
                'verbose_name_plural': 'Blog Recently Added',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
