# Generated by Django 6.0.3 on 2026-06-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogbrandlogo_blogcategory_blogdiscountbanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Brand Logo', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/brands/')),
                ('text_logo', models.CharField(blank=True, default='', max_length=80)),
                ('url', models.URLField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Brand Logo',
                'verbose_name_plural': 'About Brand Logos',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutDeliverySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='We Delivered, You Enjoy Your Order.', max_length=180)),
                ('description', models.TextField(default='At Vetri Fresh, we ensure quick and safe delivery of your groceries right to your doorstep.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/delivery/')),
                ('point_one', models.CharField(default='Sed in metus pellentesque.', max_length=160)),
                ('point_two', models.CharField(default='Fusce et ex commodo, aliquam nulla efficitur, tempus lorem.', max_length=160)),
                ('point_three', models.CharField(default='Maecenas mi turpis fringilla erat varius.', max_length=160)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/shop', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Delivery Section',
                'verbose_name_plural': 'About Delivery Section',
            },
        ),
        migrations.CreateModel(
            name='AboutFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🌿', max_length=30)),
                ('title', models.CharField(default='100% Organic food', max_length=120)),
                ('subtitle', models.CharField(default='100% healthy & fresh food.', max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Feature Item',
                'verbose_name_plural': 'About Feature Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutFeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='100% Trusted Organic Food Store', max_length=180)),
                ('description', models.TextField(default='Pellentesque a ante vulputate leo porttitor luctus sed eget eros. Nulla et rhoncus neque.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/features/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Feature Section',
                'verbose_name_plural': 'About Feature Section',
            },
        ),
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='100% Trusted Organic Food Store', max_length=180)),
                ('description', models.TextField(default='Vetri Fresh is a trusted organic food store delivering fresh, high-quality groceries straight from farm to home.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('button_text', models.CharField(blank=True, default='', max_length=50)),
                ('button_link', models.CharField(blank=True, default='/shop', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Hero Section',
                'verbose_name_plural': 'About Hero Section',
            },
        ),
        migrations.CreateModel(
            name='AboutPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=120)),
                ('breadcrumb_text', models.CharField(default='About Us', max_length=120)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='about/banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Banner',
                'verbose_name_plural': 'About Page Banner',
            },
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(default='Team Member', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/team/')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Team Member',
                'verbose_name_plural': 'About Team Members',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(default='Customer', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/testimonials/')),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Testimonial',
                'verbose_name_plural': 'About Testimonials',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
