# Generated by Django 6.0.3 on 2026-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutbrandlogo_aboutdeliverysection_aboutfeatureitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(default='Get in Touch', max_length=120)),
                ('name_placeholder', models.CharField(default='Name', max_length=80)),
                ('email_placeholder', models.CharField(default='Email', max_length=80)),
                ('phone_placeholder', models.CharField(default='Phone Number', max_length=80)),
                ('message_placeholder', models.CharField(default='Message', max_length=80)),
                ('submit_button_text', models.CharField(default='Submit', max_length=50)),
                ('recipient_email', models.EmailField(default='padmavathyprasanna4@gmail.com', max_length=254)),
                ('email_subject_prefix', models.CharField(default='VetriFresh Contact Message', max_length=120)),
                ('form_background_image', models.ImageField(blank=True, null=True, upload_to='contact/form-bg/')),
                ('form_bg_color', models.CharField(default='#7ccf8d', max_length=20)),
                ('contact_card_bg_color', models.CharField(default='#e4f8bf', max_length=20)),
                ('map_embed_url', models.TextField(blank=True, default='https://www.google.com/maps?q=Soorandi,Tenkasi&output=embed', help_text='Paste Google Maps embed URL or use a query URL like https://www.google.com/maps?q=Tenkasi&output=embed')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='contact/map/')),
                ('map_height', models.PositiveIntegerField(default=320)),
                ('success_message', models.CharField(default='Message sent successfully.', max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Form Setting',
                'verbose_name_plural': 'Contact Form Setting',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(choices=[('location', 'Location'), ('email', 'Email'), ('phone', 'Phone'), ('custom', 'Custom')], default='location', max_length=20)),
                ('custom_icon', models.CharField(blank=True, default='', max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('line_one', models.CharField(max_length=180)),
                ('line_two', models.CharField(blank=True, default='', max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info Item',
                'verbose_name_plural': 'Contact Info Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact', max_length=120)),
                ('breadcrumb_text', models.CharField(default='Contact', max_length=120)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='contact/banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Page Banner',
                'verbose_name_plural': 'Contact Page Banner',
            },
        ),
    ]
