# Generated by Django 6.0.3 on 2026-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactformsetting_contactinfoitem_contactmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cash on Delivery', max_length=80)),
                ('method_type', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Cashfree', 'Cashfree Payment Gateway'), ('UPI', 'UPI'), ('Card', 'Card Payment'), ('Net Banking', 'Net Banking')], default='Cash on Delivery', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('icon', models.CharField(blank=True, default='', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Checkout Payment Method',
                'verbose_name_plural': 'Checkout Payment Methods',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cashfree_order_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cashfree_payment_session_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cashfree_status',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_message',
            field=models.CharField(default='We will knock your door steps shortly.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(default='Order Placed', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactformsetting',
            name='recipient_email',
            field=models.EmailField(default='padmavathyparasanna4@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Cashfree', 'Cashfree Payment Gateway'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], default='Cash on Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
