# Generated by Django 6.0.3 on 2026-06-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paymentmethod_order_cashfree_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramimage',
            name='animation',
            field=models.CharField(choices=[('fade-up', 'Fade Up'), ('zoom-in', 'Zoom In'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('flip', 'Flip'), ('none', 'No Animation')], default='fade-up', max_length=30),
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='animation_delay_seconds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delay before this image animates. Example: 0.40 seconds.', max_digits=4),
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='animation_duration_seconds',
            field=models.DecimalField(decimal_places=2, default=0.6, help_text='Animation speed in seconds. Example: 0.60.', max_digits=4),
        ),
        migrations.AddField(
            model_name='promocard',
            name='button_bg_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AddField(
            model_name='promocard',
            name='button_text_color',
            field=models.CharField(default='#00B207', max_length=20),
        ),
        migrations.AddField(
            model_name='promocard',
            name='content_animation',
            field=models.CharField(choices=[('fade-up', 'Fade Up'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('none', 'No Animation')], default='fade-up', max_length=30),
        ),
        migrations.AddField(
            model_name='promocard',
            name='image_height_percent',
            field=models.PositiveIntegerField(default=52, help_text='Promo image height in percent for bottom image styles. Example: 52.'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='image_position',
            field=models.CharField(choices=[('bottom-cover', 'Bottom image - cover'), ('bottom-contain', 'Bottom image - contain'), ('right-contain', 'Right image - contain'), ('full-cover', 'Full card image')], default='bottom-cover', help_text='Choose how the promo image should be placed inside the card.', max_length=20),
        ),
        migrations.AddField(
            model_name='promocard',
            name='overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Dark overlay over image from 0.00 to 1.00. Use 0 to remove dark background.', max_digits=3),
        ),
        migrations.AddField(
            model_name='promocard',
            name='promo_style',
            field=models.CharField(choices=[('dark', 'Dark top with image bottom'), ('yellow', 'Yellow fresh fruit style'), ('light', 'Light clean card'), ('image', 'Image focus'), ('custom', 'Custom colors')], default='dark', help_text='Controls the card layout/style on the home page.', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocard',
            name='bg_color',
            field=models.CharField(default='#073B14', help_text='Used by Custom style and as fallback for dark/light styles.', max_length=20),
        ),
    ]
